name: Update Github Stats

on:
  schedule:
    - cron: "47 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install requirements
        run: |
          npm install
          
      - name: Github Configurations
        run: |
          git config --global user.name "IMTR0J4N"
          git config --global user.email "jjorgebeau.pro@gmail.com"
          git pull
          
      - name: Update Template
        run: |
          node updater.js IMTR0J4N googledark
        env:
          GHT: ${{ secrets.GHT }}
          
      - name: Commit changed SVG template
        run: |
          git add .
          git commit -m "Github Stats updated 🎉" || echo
          git push
